---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 81908.
--- DateTime: 2023/12/14 11:03
---
local skynet = require "skynet"
local s = require "service"

s.client = {}

s.resp.client = function(source,fd,cmd,msg)
    --skynet.error("[login] receive cmd:"..cmd)
    if s.client[cmd] then
        local ret_msg = s.client[cmd](fd,msg,source)
        skynet.send(source,"lua","send_by_fd",fd,ret_msg)
    else
        skynet.error("s.resp.client fail",cmd)
    end
end

function s.init()
    skynet.error("[login start] "..s.name..s.id)
end


s.start(...)


s.client.login = function(fd, msg, source)
    skynet.error("login recv "..msg[1].." "..msg[2])
    --[[
    login验证密码
    失败：返回失败消息给agent
    成功：请求agentmgr分配agent
    ]]--
    local player_id = tonumber(msg[2])
    local pwd = msg[3]

    if pwd ~= "123" then
        return {"login",1,"密码错误"}
    end

    local node = skynet.getenv("node")
    local gate = source

    local isOk,agent = skynet.call("agentmgr","lua","req_login",player_id,node,gate)

    if not isOk then
        return {"login",1,"请求mgr失败"}
    end

    --  回应gate
    local isSuccess = skynet.call(gate,"lua","sure_agent",fd,player_id,agent)

    if not isSuccess then
        return {"login",1,"gate注册失败"}
    end
    skynet.error("login success "..player_id)

    return {"login",0,"登录成功"}
end